name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  unit-test:
    name: unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: istall dependecies
        run: npm ci
      - name: lint
        run: npm run lint
