name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]
jobs:
  unit-test:
    name: unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: istall dependecies
        run: npm ci
      - name: lint
        run: npm run lint
  deploy:
    name: deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [unit-test, lint]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'will deploy'
      # - uses: actions/checkout@v2
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "YOUR APP's NAME"
      #     heroku_email: 'YOUR EMAIL'
